services:
  ryu:
    image: ryu-debian
    container_name: ryu
    command: ["--ofp-tcp-listen-port", "6633", "--observe-links", "/apps/test_app.py"]
    volumes:
    - ./apps:/apps
    networks:
      sdn_net:
        ipv4_address: 172.16.0.2
    ports:
      - "6633:6633"   
      - "8080:8080"   
    tty: true

  mininet:
    build:
      context: .
    image: iwaseyusuke/mininet:ubuntu-22.04  
    container_name: mininet
    tty: true
    privileged: true
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /lib/modules:/lib/modules
      - .:/ssp-project
    working_dir: /ssp-project
    networks:
      sdn_net:
        ipv4_address: 172.16.0.3
    #entrypoint: ["/bin/bash", "/ssp-project/scenarios/startup.sh"]    
    
networks:
  sdn_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16
