services:
  ryu:
    image: ryu-alpine
    container_name: ryu
    command: ["--ofp-tcp-listen-port", "6633", "ryu.app.simple_switch_stp_13"]
    networks:
      sdn_net:
        ipv4_address: 172.16.0.2
    ports:
      - "6633:6633"   # OpenFlow
      - "8080:8080"   # REST API (if your Ryu app exposes it)
    tty: true

  mininet:
    build:
      context: .
    image: iwaseyusuke/mininet:ubuntu-22.04  
    container_name: mininet
    tty: true
    privileged: true
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /lib/modules:/lib/modules
      - .:/ssp-project
    networks:
      sdn_net:
        ipv4_address: 172.16.0.3
    entrypoint: ["bash", "/ssp-project/startup.sh"]

networks:
  sdn_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16
