services:
  ryu:
    image: ryu-alpine
    container_name: ryu
    # command: python3 -m ryu.cmd.manager --ofp-tcp-listen-port 6633 ryu.app.simple_switch
    # command does not work, cant figure this out -Krzysiek
    networks:
      sdn_net:
        ipv4_address: 172.16.0.2
    ports:
      - "6633:6633"   # OpenFlow
      - "8080:8080"   # REST API (if your Ryu app exposes it)
    tty: true

  mininet:
    build:
      context: .
    image: iwaseyusuke/mininet:ubuntu-22.04  
    container_name: mininet
    tty: true
    privileged: true
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /lib/modules:/lib/modules
      - .:/ssp-project
    networks:
      sdn_net:
        ipv4_address: 172.16.0.3
    command: bash -c "mn --controller=remote,ip=172.16.0.2 --topo single,3"

networks:
  sdn_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16
